# Caddyfile - Matrix Stack Reverse Proxy
# Generated by Matrix Stack Setup
# Do not edit manually — re-run setup to reconfigure.

# Global options
{
	admin off
{{#DNS_CHALLENGE}}
	acme_dns cloudflare {env.CF_API_TOKEN}
{{/DNS_CHALLENGE}}
}

# Shared security headers snippet
(security_headers) {
	header {
		Strict-Transport-Security "max-age=63072000; includeSubDomains; preload"
		X-Content-Type-Options "nosniff"
		X-Frame-Options "DENY"
		Referrer-Policy "strict-origin-when-cross-origin"
		Permissions-Policy "accelerometer=(), camera=(), geolocation=(), gyroscope=(), magnetometer=(), microphone=(), payment=(), usb=()"
		X-XSS-Protection "0"
		-Server
	}
}

# --- Main domain: Matrix homeserver ---
{{DOMAIN}} {
	import security_headers

	# .well-known for Matrix client discovery
	handle /.well-known/matrix/client {
		header Content-Type "application/json"
		header Access-Control-Allow-Origin "*"
		respond `{"m.homeserver":{"base_url":"https://{{DOMAIN}}"}}`
	}

	# .well-known for Matrix server discovery (federation)
	handle /.well-known/matrix/server {
		header Content-Type "application/json"
		respond `{"m.server":"{{DOMAIN}}:443"}`
	}

	# Proxy all Matrix client and federation API requests
	handle /_matrix/* {
		reverse_proxy {{HS_BACKEND}} {
			header_up X-Forwarded-Proto {scheme}
			header_up X-Forwarded-For {remote_host}
			transport http {
				read_timeout 600s
				write_timeout 600s
			}
		}
	}

	# Synapse admin API
	handle /_synapse/* {
		reverse_proxy {{HS_BACKEND}} {
			header_up X-Forwarded-Proto {scheme}
			header_up X-Forwarded-For {remote_host}
		}
	}

	# Default: return 404 for everything else on the main domain
	handle {
		respond "Not Found" 404
	}
}

{{#FEDERATION}}
# --- Federation port (8448) ---
{{DOMAIN}}:{{FEDERATION_PORT}} {
	import security_headers

	reverse_proxy {{HS_BACKEND}} {
		header_up X-Forwarded-Proto {scheme}
		header_up X-Forwarded-For {remote_host}
		transport http {
			read_timeout 600s
			write_timeout 600s
		}
	}
}
{{/FEDERATION}}

{{#WEBCLIENT}}
# --- Web Client ---
{{WEBCLIENT_SUBDOMAIN}}.{{DOMAIN}} {
	import security_headers

	header Content-Security-Policy "{{WEBCLIENT_CSP}}"

	reverse_proxy {{WEBCLIENT_BACKEND}} {
		header_up X-Forwarded-Proto {scheme}
		header_up X-Forwarded-For {remote_host}
	}
}
{{/WEBCLIENT}}

{{#ADMIN_UI}}
# --- Synapse Admin UI ---
{{ADMIN_SUBDOMAIN}}.{{DOMAIN}} {
	import security_headers

	header Content-Security-Policy "default-src 'self'; script-src 'self' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; img-src 'self' data:; connect-src 'self' https://{{DOMAIN}}; frame-ancestors 'none'"

	reverse_proxy {{ADMIN_BACKEND}} {
		header_up X-Forwarded-Proto {scheme}
		header_up X-Forwarded-For {remote_host}
	}
}
{{/ADMIN_UI}}

{{#GRAFANA}}
# --- Grafana Monitoring ---
{{GRAFANA_SUBDOMAIN}}.{{DOMAIN}} {
	import security_headers

	reverse_proxy {{GRAFANA_BACKEND}} {
		header_up X-Forwarded-Proto {scheme}
		header_up X-Forwarded-For {remote_host}
	}
}
{{/GRAFANA}}
