# Dendrite Homeserver Configuration (Monolith Mode)
# Generated by Matrix Stack Setup v{{MATRIX_SETUP_VERSION}}
# Do not edit manually — re-run setup to reconfigure.

version: 2

global:
  server_name: "{{SERVER_NAME}}"
  private_key: "{{SIGNING_KEY_PATH}}"
  well_known_server_name: "{{DOMAIN}}:443"
  well_known_client_name: "https://{{DOMAIN}}"
  trusted_third_party_id_servers:
    - matrix.org
    - vector.im
  key_validity_period: "168h0m0s"
  database:
    connection_string: "postgresql://{{DB_USER}}:{{DB_PASSWORD}}@{{DB_HOST}}:{{DB_PORT}}/{{DB_NAME}}?sslmode=disable"
    max_open_conns: 90
    max_idle_conns: 5
    conn_max_lifetime: -1
  cache:
    max_size_estimated: "512mb"
    max_age: "1h"
  jetstream:
    storage_path: "/data/jetstream"
    in_memory: false
  metrics:
{{#METRICS}}
    enabled: true
{{/METRICS}}
  dns_cache:
    enabled: true
    cache_size: 256
    cache_lifetime: "5m"
{{#TURN}}
  turn:
    turn_uris:
      - "{{TURN_URI_UDP}}"
      - "{{TURN_URI_TCP}}"
      - "{{TURN_URI_TLS}}"
    turn_shared_secret: "{{TURN_SHARED_SECRET}}"
    turn_user_lifetime: "24h"
{{/TURN}}

app_service_api:
  database:
    connection_string: "postgresql://{{DB_USER}}:{{DB_PASSWORD}}@{{DB_HOST}}:{{DB_PORT}}/{{DB_NAME}}?sslmode=disable"

client_api:
  registration_disabled: {{ENABLE_REGISTRATION}}
  registration_shared_secret: "{{REGISTRATION_SHARED_SECRET}}"
  rate_limiting:
    enabled: true
    threshold: 20
    cooloff_ms: 500

federation_api:
{{#FEDERATION}}
  send_max_retries: 16
  disable_tls_validation: false
  prefer_direct_fetch: false
  database:
    connection_string: "postgresql://{{DB_USER}}:{{DB_PASSWORD}}@{{DB_HOST}}:{{DB_PORT}}/{{DB_NAME}}?sslmode=disable"
{{/FEDERATION}}

media_api:
  base_path: "/data/media_store"
  max_file_size_bytes: 104857600
  dynamic_thumbnails: false
  max_thumbnail_generators: 10
  database:
    connection_string: "postgresql://{{DB_USER}}:{{DB_PASSWORD}}@{{DB_HOST}}:{{DB_PORT}}/{{DB_NAME}}?sslmode=disable"

mscs:
  mscs: []

room_server:
  database:
    connection_string: "postgresql://{{DB_USER}}:{{DB_PASSWORD}}@{{DB_HOST}}:{{DB_PORT}}/{{DB_NAME}}?sslmode=disable"

sync_api:
  real_ip_header: "X-Forwarded-For"
  database:
    connection_string: "postgresql://{{DB_USER}}:{{DB_PASSWORD}}@{{DB_HOST}}:{{DB_PORT}}/{{DB_NAME}}?sslmode=disable"

user_api:
  auto_join_rooms: []
  database:
    connection_string: "postgresql://{{DB_USER}}:{{DB_PASSWORD}}@{{DB_HOST}}:{{DB_PORT}}/{{DB_NAME}}?sslmode=disable"

key_server:
  database:
    connection_string: "postgresql://{{DB_USER}}:{{DB_PASSWORD}}@{{DB_HOST}}:{{DB_PORT}}/{{DB_NAME}}?sslmode=disable"

logging:
  - type: std
    level: info
