# Synapse Homeserver Configuration
# Generated by Matrix Stack Setup v{{MATRIX_SETUP_VERSION}}
# Do not edit manually — re-run setup to reconfigure.

server_name: "{{SERVER_NAME}}"
public_baseurl: "https://{{DOMAIN}}"
pid_file: "/data/homeserver.pid"
web_client_location: "https://{{WEBCLIENT_SUBDOMAIN}}.{{DOMAIN}}/"
serve_server_wellknown: true

# --- Listeners ---
listeners:
  - port: 8008
    tls: false
    type: http
    x_forwarded: true
    bind_addresses: ['0.0.0.0']
    resources:
      - names: [client, federation]
        compress: false
{{#METRICS}}
  - port: 9000
    tls: false
    type: metrics
    bind_addresses: ['0.0.0.0']
{{/METRICS}}

# --- Database ---
database:
  name: psycopg2
  txn_limit: 10000
  args:
    user: "{{DB_USER}}"
    password: "{{DB_PASSWORD}}"
    database: "{{DB_NAME}}"
    host: "{{DB_HOST}}"
    port: "{{DB_PORT}}"
    cp_min: 5
    cp_max: 10

# --- Logging ---
log_config: "/data/log.config"

# Log to file for fail2ban integration
# Synapse also logs to stdout for container log collection

# --- Media ---
media_store_path: "/data/media_store"
max_upload_size: "100M"
url_preview_enabled: true
url_preview_ip_range_blacklist:
  - '127.0.0.0/8'
  - '10.0.0.0/8'
  - '172.16.0.0/12'
  - '192.168.0.0/16'
  - '100.64.0.0/10'
  - '192.0.0.0/24'
  - '169.254.0.0/16'
  - '198.18.0.0/15'
  - '::1/128'
  - 'fe80::/10'
  - 'fc00::/7'
  - '::ffff:0:0/96'

# Remote media retention
{{#FEDERATION}}
media_retention:
  remote_media_lifetime: "{{MEDIA_RETENTION_DAYS}}d"
{{/FEDERATION}}

# --- Signing Keys ---
signing_key_path: "{{SIGNING_KEY_PATH}}"

# --- Registration ---
enable_registration: {{ENABLE_REGISTRATION}}
{{#REGISTRATION_REQUIRES_TOKEN}}
registration_requires_token: true
{{/REGISTRATION_REQUIRES_TOKEN}}
registration_shared_secret: "{{REGISTRATION_SHARED_SECRET}}"

{{#REGISTRATIONS_REQUIRE_3PID}}
registrations_require_3pid:
  - email
{{/REGISTRATIONS_REQUIRE_3PID}}

{{#ENABLE_CAPTCHA}}
enable_registration_captcha: true
recaptcha_public_key: "{{RECAPTCHA_PUBLIC_KEY}}"
recaptcha_private_key: "{{RECAPTCHA_PRIVATE_KEY}}"
{{/ENABLE_CAPTCHA}}

# --- Federation ---
{{#FEDERATION}}
federation_domain_whitelist: null
allow_public_rooms_over_federation: true
default_room_version: "{{DEFAULT_ROOM_VERSION}}"
{{/FEDERATION}}

# --- TURN ---
{{#TURN}}
turn_uris:
  - "{{TURN_URI_UDP}}"
  - "{{TURN_URI_TCP}}"
  - "{{TURN_URI_TLS}}"
turn_shared_secret: "{{TURN_SHARED_SECRET}}"
turn_user_lifetime: 86400000
turn_allow_guests: true
{{/TURN}}

# --- SMTP ---
{{#SMTP}}
email:
  smtp_host: "{{SMTP_HOST}}"
  smtp_port: {{SMTP_PORT}}
  smtp_user: "{{SMTP_USER}}"
  smtp_pass: "{{SMTP_PASS}}"
  notif_from: "%(app)s <{{SMTP_FROM}}>"
  enable_notifs: true
  notif_for_new_users: true
{{/SMTP}}

# --- Secrets ---
macaroon_secret_key: "{{MACAROON_SECRET_KEY}}"
form_secret: "{{FORM_SECRET}}"

# --- Rate limiting ---
rc_message:
  per_second: 0.2
  burst_count: 10
rc_registration:
  per_second: 0.17
  burst_count: 3
rc_login:
  address:
    per_second: 0.17
    burst_count: 3
  account:
    per_second: 0.17
    burst_count: 3

# --- Caching ---
caches:
  global_factor: 0.5

# --- Content ---
suppress_key_server_warning: true
enable_search: true

# --- Metrics ---
{{#METRICS}}
enable_metrics: true
{{/METRICS}}

# --- Appservice registrations ---
app_service_config_files: []

# --- Trusted key servers ---
trusted_key_servers:
  - server_name: "matrix.org"

# --- Report stats (opt-out) ---
report_stats: false
