# Coturn TURN/STUN Server Configuration
# Generated by Matrix Stack Setup
# Hardened against CVE-2026-27624 (SSRF via TURN relay)
# Do not edit manually — re-run setup to reconfigure.

# --- Listening ---
listening-port={{STUN_PORT}}
tls-listening-port={{STUN_TLS_PORT}}
min-port={{MIN_PORT}}
max-port={{MAX_PORT}}

# External address (use domain for NAT traversal)
realm={{DOMAIN}}
server-name={{DOMAIN}}

# --- Authentication ---
# Long-term credential mechanism with shared secret (recommended for Matrix)
lt-cred-mech
use-auth-secret
static-auth-secret={{TURN_SECRET}}

# --- TLS ---
{{#TLS}}
cert={{TLS_CERT_DIR}}/cert.pem
pkey={{TLS_CERT_DIR}}/privkey.pem
{{/TLS}}

# --- Relay hardening (CVE-2026-27624 mitigations) ---
# Block relay to private/loopback networks to prevent SSRF

# IPv4 private ranges (RFC 1918)
denied-peer-ip=10.0.0.0-10.255.255.255
denied-peer-ip=172.16.0.0-172.31.255.255
denied-peer-ip=192.168.0.0-192.168.255.255

# IPv4 loopback
denied-peer-ip=127.0.0.0-127.255.255.255

# IPv4 link-local
denied-peer-ip=169.254.0.0-169.254.255.255

# IPv4 shared address space (RFC 6598)
denied-peer-ip=100.64.0.0-100.127.255.255

# IPv4 documentation/TEST-NET
denied-peer-ip=192.0.2.0-192.0.2.255
denied-peer-ip=198.51.100.0-198.51.100.255
denied-peer-ip=203.0.113.0-203.0.113.255

# IPv4 benchmarking (RFC 2544)
denied-peer-ip=198.18.0.0-198.19.255.255

# IPv6 loopback
denied-peer-ip=::1-::1

# IPv6 link-local
denied-peer-ip=fe80::-febf::ffff:ffff:ffff:ffff:ffff:ffff:ffff

# IPv6 unique local (RFC 4193)
denied-peer-ip=fc00::-fdff::ffff:ffff:ffff:ffff:ffff:ffff:ffff

# IPv4-mapped IPv6 addresses (critical for CVE-2026-27624)
denied-peer-ip=::ffff:0.0.0.0-::ffff:255.255.255.255

# IPv6 documentation
denied-peer-ip=2001:db8::-2001:db8::ffff:ffff:ffff:ffff:ffff:ffff

# --- Protocol hardening ---
no-multicast-peers
no-rfc5780
no-cli

# Disable old/insecure auth methods
no-tlsv1
no-tlsv1_1

# NOTE: 'no-udp-relay' is intentionally NOT set. It would disable UDP media
# relay entirely and break WebRTC voice/video (Coturn's core purpose). The SSRF
# vector (CVE-2026-27624) is already mitigated by the denied-peer-ip rules above.

# --- Rate limiting ---
# Per-user bandwidth limit (bytes/sec) — 10 Mbps
max-bps=10000000

# Max allocations per user
user-quota=12

# Max total allocations on the server
total-quota=1200

# Stale nonce lifetime
stale-nonce=600

# --- Logging ---
log-file=stdout
verbose

# --- Fingerprinting ---
fingerprint

{{#IPV6}}
# --- IPv6 ---
listening-ip=0.0.0.0
listening-ip=::
relay-ip=0.0.0.0
relay-ip=::
{{/IPV6}}
