#!/usr/bin/env bash
# Matrix Stack Setup - Monitoring (Prometheus + Grafana)
set -euo pipefail

monitoring_setup() {
    log_step "Configuring monitoring stack"

    if [[ "${CONFIG[monitoring.enabled]:-false}" != "true" ]]; then
        log_substep "Monitoring disabled, skipping"
        return 0
    fi

    local install_dir="${CONFIG[install_dir]:-$DEFAULT_INSTALL_DIR}"
    local config_dir="$install_dir/config/monitoring"
    local domain="${CONFIG[domain.name]}"
    local grafana_sub="${CONFIG[monitoring.grafana_subdomain]:-grafana}"

    mkdir -p "$config_dir/grafana/provisioning/datasources" \
             "$config_dir/grafana/provisioning/dashboards" \
             "$config_dir/grafana/dashboards"

    CONFIG[monitoring.prometheus_image]="$PROMETHEUS_IMAGE"
    CONFIG[monitoring.grafana_image]="$GRAFANA_IMAGE"

    _monitoring_prometheus_config "$config_dir"
    _monitoring_grafana_provisioning "$config_dir"

    log_substep "Grafana will be available at https://${grafana_sub}.${domain}"
    log_success "Monitoring stack configured"
}

_monitoring_prometheus_config() {
    local config_dir="$1"
    local hs_type="${CONFIG[homeserver.type]:-synapse}"

    local hs_target
    if [[ "${COMPOSE_NETWORKING:-dns}" == "pod" ]]; then
        hs_target="localhost:9000"
    else
        hs_target="homeserver:9000"
    fi

    cat > "$config_dir/prometheus.yml" << PROMYML
# Prometheus configuration
# Generated by Matrix Stack Setup

global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: '${hs_type}'
    metrics_path: '/_synapse/metrics'
    static_configs:
      - targets: ['${hs_target}']
    scrape_interval: 15s

  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']
    scrape_interval: 30s
PROMYML

    rollback_snapshot "monitoring" "FILE_CREATED" "$config_dir/prometheus.yml"
    log_substep "Prometheus config written"
}

_monitoring_grafana_provisioning() {
    local config_dir="$1"

    # Datasource provisioning
    cat > "$config_dir/grafana/provisioning/datasources/prometheus.yml" << GRAFDS
apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: false
GRAFDS

    # Dashboard provisioning
    cat > "$config_dir/grafana/provisioning/dashboards/default.yml" << GRAFDASH
apiVersion: 1

providers:
  - name: 'default'
    orgId: 1
    folder: 'Matrix'
    type: file
    disableDeletion: false
    editable: true
    options:
      path: /var/lib/grafana/dashboards
      foldersFromFilesStructure: true
GRAFDASH

    # Minimal Synapse overview dashboard
    cat > "$config_dir/grafana/dashboards/synapse-overview.json" << 'DASHJSON'
{
  "annotations": {"list": []},
  "editable": true,
  "fiscalYearStartMonth": 0,
  "graphTooltip": 0,
  "id": null,
  "links": [],
  "liveNow": false,
  "panels": [
    {
      "datasource": {"type": "prometheus", "uid": "prometheus"},
      "fieldConfig": {"defaults": {"unit": "short"}},
      "gridPos": {"h": 8, "w": 12, "x": 0, "y": 0},
      "title": "Active Users (5m)",
      "type": "stat",
      "targets": [{"expr": "synapse_current_active_users", "legendFormat": "Active Users"}]
    },
    {
      "datasource": {"type": "prometheus", "uid": "prometheus"},
      "fieldConfig": {"defaults": {"unit": "reqps"}},
      "gridPos": {"h": 8, "w": 12, "x": 12, "y": 0},
      "title": "Request Rate",
      "type": "timeseries",
      "targets": [{"expr": "rate(synapse_http_server_requests_received_total[5m])", "legendFormat": "{{method}} {{servlet}}"}]
    },
    {
      "datasource": {"type": "prometheus", "uid": "prometheus"},
      "fieldConfig": {"defaults": {"unit": "bytes"}},
      "gridPos": {"h": 8, "w": 12, "x": 0, "y": 8},
      "title": "Memory Usage",
      "type": "timeseries",
      "targets": [{"expr": "process_resident_memory_bytes{job=\"synapse\"}", "legendFormat": "RSS"}]
    },
    {
      "datasource": {"type": "prometheus", "uid": "prometheus"},
      "fieldConfig": {"defaults": {"unit": "short"}},
      "gridPos": {"h": 8, "w": 12, "x": 12, "y": 8},
      "title": "Federation Events",
      "type": "timeseries",
      "targets": [
        {"expr": "rate(synapse_federation_client_sent_transactions_total[5m])", "legendFormat": "Sent"},
        {"expr": "rate(synapse_federation_server_received_pdus_total[5m])", "legendFormat": "Received"}
      ]
    }
  ],
  "schemaVersion": 39,
  "tags": ["matrix", "synapse"],
  "templating": {"list": []},
  "time": {"from": "now-6h", "to": "now"},
  "title": "Synapse Overview",
  "uid": "synapse-overview"
}
DASHJSON

    rollback_snapshot "monitoring" "FILE_CREATED" "$config_dir/grafana/provisioning/datasources/prometheus.yml"
    log_substep "Grafana provisioning written"
}
