#!/usr/bin/env bash
# Matrix Stack Setup - Quadlet Systemd Integration
# Generates .container and .network Quadlet units for auto-start on boot.
set -euo pipefail

quadlet_setup() {
    log_step "Setting up Quadlet systemd integration"

    local install_dir="${CONFIG[install_dir]:-$DEFAULT_INSTALL_DIR}"
    local matrix_user="${CONFIG[matrix_user]:-$DEFAULT_MATRIX_USER}"
    local user_home
    user_home=$(get_user_home "$matrix_user")

    # Rootless Quadlet directory (Quadlet sources) and the systemd user unit
    # directory (plain .service units).
    local quadlet_dir="${user_home}/.config/containers/systemd"
    local systemd_user_dir="${user_home}/.config/systemd/user"
    mkdir -p "$quadlet_dir" "$systemd_user_dir"

    # Generate main pod/compose unit
    _quadlet_generate_compose "$quadlet_dir" "$install_dir" "$systemd_user_dir"

    # Coturn runs rootful — separate Quadlet at system level
    if [[ "${CONFIG[coturn.enabled]:-true}" == "true" ]]; then
        _quadlet_generate_coturn "$install_dir"
    fi

    # Reload systemd
    log_substep "Reloading systemd..."
    run_as_user systemctl --user daemon-reload 2>/dev/null || true

    if [[ "${CONFIG[coturn.enabled]:-true}" == "true" ]]; then
        systemctl daemon-reload 2>/dev/null || true
    fi

    rollback_snapshot "quadlet" "QUADLET_INSTALLED" "$quadlet_dir"
    log_success "Quadlet units installed"
}

_quadlet_generate_compose() {
    local quadlet_dir="$1"
    local install_dir="$2"
    local systemd_user_dir="$3"

    # The stack is defined by podman-compose.yml, so there is no second,
    # per-service Quadlet definition of it: a `.container` unit needs an
    # `Image=` ("There is only one required key, Image" — podman-systemd.unit(5))
    # and one unit per service would restate every image, volume and network
    # the compose file already carries. The compose wrapper below is the single
    # boot path.

    # Compose wrapper as a PLAIN systemd user .service (not a Quadlet source).
    # A '.kube' Quadlet suffix is for `podman kube play` Kubernetes YAML and must
    # contain a [Kube] section; using it with a [Service] section is rejected or
    # mishandled by the Quadlet generator. A service wrapper around a compose
    # command is an ordinary systemd unit, so it belongs in the user unit dir.
    cat > "$systemd_user_dir/matrix-compose.service" << UNIT
# Matrix Stack Compose service
# Generated by Matrix Stack Setup
# Runs podman-compose via a systemd service instead of individual .container units

[Unit]
Description=Matrix Communication Stack (compose)
After=network-online.target
Wants=network-online.target

[Service]
Type=oneshot
RemainAfterExit=yes
WorkingDirectory=${install_dir}
ExecStart=${COMPOSE_CMD} -f ${install_dir}/podman-compose.yml up -d
ExecStop=${COMPOSE_CMD} -f ${install_dir}/podman-compose.yml down
TimeoutStartSec=300
TimeoutStopSec=120

[Install]
WantedBy=default.target
UNIT

    systemd_user_enable_unit "$systemd_user_dir" "matrix-compose.service" "default.target"

    chown -R "${CONFIG[matrix_user]:-$DEFAULT_MATRIX_USER}:" "$quadlet_dir" "$systemd_user_dir"
    log_substep "Rootless units written to $quadlet_dir and $systemd_user_dir"
    log_substep "matrix-compose.service enabled for boot (default.target.wants)"
}

_quadlet_generate_coturn() {
    local install_dir="$1"
    local system_quadlet="${QUADLET_SYSTEM_DIR:-/etc/containers/systemd}"
    mkdir -p "$system_quadlet"

    # turnserver.conf references /etc/coturn/certs when TLS is on, so the unit
    # has to carry the same mount the compose fragment does.
    local volumes="Volume=${install_dir}/config/turnserver.conf:/etc/coturn/turnserver.conf:ro"
    if [[ "${CONFIG[coturn.tls]:-false}" == "true" && -n "${CONFIG[coturn.cert_dir]:-}" ]]; then
        volumes+=$'\n'"Volume=${CONFIG[coturn.cert_dir]}:/etc/coturn/certs:ro"
    fi

    cat > "$system_quadlet/matrix-coturn.container" << UNIT
# Coturn TURN/STUN Quadlet Unit (rootful)
# Generated by Matrix Stack Setup

[Unit]
Description=Matrix Coturn TURN/STUN Server
After=network-online.target
Wants=network-online.target

[Container]
ContainerName=matrix-coturn
Image=${COTURN_IMAGE}
Network=host
${volumes}
Exec=-c /etc/coturn/turnserver.conf

[Service]
Restart=on-failure
RestartSec=10
TimeoutStartSec=60

[Install]
WantedBy=multi-user.target
UNIT

    rollback_snapshot "quadlet" "FILE_CREATED" "$system_quadlet/matrix-coturn.container"
    log_substep "Coturn Quadlet unit written to $system_quadlet/"
}
