#!/usr/bin/env bash
# Matrix Stack Setup - Quadlet Systemd Integration
# Generates .container and .network Quadlet units for auto-start on boot.
set -euo pipefail

quadlet_setup() {
    log_step "Setting up Quadlet systemd integration"

    local install_dir="${CONFIG[install_dir]:-$DEFAULT_INSTALL_DIR}"
    local matrix_user="${CONFIG[matrix_user]:-$DEFAULT_MATRIX_USER}"
    local user_home
    user_home=$(eval echo "~${matrix_user}")

    # Rootless Quadlet directory
    local quadlet_dir="${user_home}/.config/containers/systemd"
    mkdir -p "$quadlet_dir"

    # Generate main pod/compose Quadlet unit
    _quadlet_generate_compose "$quadlet_dir" "$install_dir"

    # Coturn runs rootful — separate Quadlet at system level
    if [[ "${CONFIG[coturn.enabled]:-true}" == "true" ]]; then
        _quadlet_generate_coturn "$install_dir"
    fi

    # Reload systemd
    log_substep "Reloading systemd..."
    run_as_user systemctl --user daemon-reload 2>/dev/null || true

    if [[ "${CONFIG[coturn.enabled]:-true}" == "true" ]]; then
        systemctl daemon-reload 2>/dev/null || true
    fi

    rollback_snapshot "quadlet" "QUADLET_INSTALLED" "$quadlet_dir"
    log_success "Quadlet units installed"
}

_quadlet_generate_compose() {
    local quadlet_dir="$1"
    local install_dir="$2"

    cat > "$quadlet_dir/matrix-stack.container" << UNIT
# Matrix Stack Quadlet Unit
# Generated by Matrix Stack Setup

[Unit]
Description=Matrix Communication Stack
After=network-online.target
Wants=network-online.target

[Container]
ContainerName=matrix-stack
PodmanArgs=--userns=keep-id

[Service]
Restart=on-failure
RestartSec=10
TimeoutStartSec=300

[Install]
WantedBy=default.target
UNIT

    # Simpler approach: use a kube/compose Quadlet
    cat > "$quadlet_dir/matrix-compose.kube" << UNIT
# Matrix Stack Compose Quadlet
# Generated by Matrix Stack Setup
# This uses podman-compose via a systemd service instead of individual .container units

[Unit]
Description=Matrix Communication Stack (compose)
After=network-online.target
Wants=network-online.target

[Service]
Type=oneshot
RemainAfterExit=yes
WorkingDirectory=${install_dir}
ExecStart=${COMPOSE_CMD} -f ${install_dir}/podman-compose.yml up -d
ExecStop=${COMPOSE_CMD} -f ${install_dir}/podman-compose.yml down
TimeoutStartSec=300
TimeoutStopSec=120

[Install]
WantedBy=default.target
UNIT

    chown -R "${CONFIG[matrix_user]:-$DEFAULT_MATRIX_USER}:" "$quadlet_dir"
    log_substep "Rootless Quadlet units written to $quadlet_dir"
}

_quadlet_generate_coturn() {
    local install_dir="$1"
    local system_quadlet="/etc/containers/systemd"
    mkdir -p "$system_quadlet"

    cat > "$system_quadlet/matrix-coturn.container" << UNIT
# Coturn TURN/STUN Quadlet Unit (rootful)
# Generated by Matrix Stack Setup

[Unit]
Description=Matrix Coturn TURN/STUN Server
After=network-online.target
Wants=network-online.target

[Container]
ContainerName=matrix-coturn
Image=${COTURN_IMAGE}
Network=host
Volume=${install_dir}/config/turnserver.conf:/etc/coturn/turnserver.conf:ro
Exec=-c /etc/coturn/turnserver.conf

[Service]
Restart=on-failure
RestartSec=10
TimeoutStartSec=60

[Install]
WantedBy=multi-user.target
UNIT

    rollback_snapshot "quadlet" "FILE_CREATED" "$system_quadlet/matrix-coturn.container"
    log_substep "Coturn Quadlet unit written to $system_quadlet/"
}
