#!/usr/bin/env bash
# Matrix Stack Setup - Backup & Restore Script Generation
set -euo pipefail

backup_setup() {
    log_step "Configuring backup and restore"

    local install_dir="${CONFIG[install_dir]:-$DEFAULT_INSTALL_DIR}"
    local scripts_dir="$install_dir/scripts"
    local domain="${CONFIG[domain.name]}"

    mkdir -p "$scripts_dir"

    _backup_generate_backup_script "$scripts_dir" "$install_dir" "$domain"
    _backup_generate_restore_script "$scripts_dir" "$install_dir" "$domain"
    _backup_install_timer "$install_dir"

    log_success "Backup/restore scripts generated"
}

_backup_generate_backup_script() {
    local scripts_dir="$1"
    local install_dir="$2"
    local domain="$3"
    local backup_dir="${CONFIG[backup.dir]:-$DEFAULT_BACKUP_DIR}"
    local retention_daily="${CONFIG[backup.retention_daily]:-$DEFAULT_BACKUP_DAILY}"
    local retention_weekly="${CONFIG[backup.retention_weekly]:-$DEFAULT_BACKUP_WEEKLY}"
    local encryption="${CONFIG[backup.encryption]:-none}"

    # Write a safely-quoted config header (printf %q) followed by the static
    # script body. Using %q rather than sed-substituting raw values means a
    # path/target containing |, &, \, whitespace or a newline cannot corrupt or
    # inject shell into this root/timer-run script.
    {
        printf '#!/usr/bin/env bash\n'
        printf '# Matrix Stack Backup Script\n'
        printf '# Generated by Matrix Stack Setup — do not edit manually.\n'
        printf 'set -euo pipefail\n\n'
        printf 'BACKUP_DIR=%q\n'       "$backup_dir"
        printf 'INSTALL_DIR=%q\n'      "$install_dir"
        printf 'DOMAIN=%q\n'           "$domain"
        printf 'RETENTION_DAILY=%q\n'  "$retention_daily"
        printf 'RETENTION_WEEKLY=%q\n' "$retention_weekly"
        printf 'ENCRYPTION=%q\n'       "$encryption"
        printf 'ENCRYPTION_KEY=%q\n'   "${CONFIG[backup.encryption_key]:-}"
        printf 'UPLOAD_METHOD=%q\n'    "${CONFIG[backup.upload]:-none}"
        printf 'UPLOAD_TARGET=%q\n'    "${CONFIG[backup.upload_target]:-}"
    } > "$scripts_dir/backup.sh"

    cat >> "$scripts_dir/backup.sh" << 'BKEOF'

TIMESTAMP=$(date +%Y%m%d_%H%M%S)
BACKUP_NAME="matrix-backup-${TIMESTAMP}"
WORK_DIR="${BACKUP_DIR}/${BACKUP_NAME}"

log() { printf '[%s] %s\n' "$(date -u +%Y-%m-%dT%H:%M:%SZ)" "$*"; }

log "Starting Matrix backup: ${BACKUP_NAME}"
mkdir -p "$WORK_DIR"

# --- 1. Database dump ---
log "Dumping PostgreSQL database..."
DB_DUMP_START=$(date -u +%Y-%m-%dT%H:%M:%SZ)

# Try container dump first, fall back to host
if podman exec matrix-postgres pg_dump -U synapse --format=custom synapse > "${WORK_DIR}/database.dump" 2>/dev/null; then
    log "Database dump completed (container)"
elif pg_dump -U synapse --format=custom synapse > "${WORK_DIR}/database.dump" 2>/dev/null; then
    log "Database dump completed (host)"
else
    log "ERROR: Database dump failed!"
    exit 1
fi

# Verify dump integrity
if pg_restore --list "${WORK_DIR}/database.dump" > /dev/null 2>&1; then
    log "Database dump integrity check passed"
else
    log "WARNING: pg_restore --list could not verify dump (pg_restore may not be installed)"
fi

# --- 2. Signing key backup (CRITICAL) ---
log "Backing up signing key..."
SIGNING_KEY_SRC="${INSTALL_DIR}/data/signing-keys"
if [[ -d "$SIGNING_KEY_SRC" ]]; then
    cp -a "$SIGNING_KEY_SRC" "${WORK_DIR}/signing-keys"
    log "Signing key backed up — PROTECT THIS FILE"
else
    log "WARNING: Signing key directory not found at ${SIGNING_KEY_SRC}"
fi

# --- 3. Media store ---
log "Backing up media store..."
MEDIA_DIR="${INSTALL_DIR}/data/media"
if [[ -d "$MEDIA_DIR" ]]; then
    cp -a "$MEDIA_DIR" "${WORK_DIR}/media"
    log "Media store backed up"
fi
MEDIA_COPY_END=$(date -u +%Y-%m-%dT%H:%M:%SZ)

# --- 4. Config ---
log "Backing up configuration..."
cp -a "${INSTALL_DIR}/config" "${WORK_DIR}/config"

# --- 5. Timestamps (consistency window) ---
cat > "${WORK_DIR}/backup-metadata.txt" << META
backup_name=${BACKUP_NAME}
domain=${DOMAIN}
pg_dump_start=${DB_DUMP_START}
media_copy_end=${MEDIA_COPY_END}
backup_completed=$(date -u +%Y-%m-%dT%H:%M:%SZ)
META

# --- 6. Create archive ---
log "Creating archive..."
ARCHIVE="${BACKUP_DIR}/${BACKUP_NAME}.tar.gz"
tar -czf "$ARCHIVE" -C "$BACKUP_DIR" "$BACKUP_NAME"
rm -rf "$WORK_DIR"

# --- 7. Optional encryption ---
if [[ "$ENCRYPTION" == "gpg" && -n "$ENCRYPTION_KEY" ]]; then
    log "Encrypting with GPG..."
    gpg --batch --yes --recipient "$ENCRYPTION_KEY" --encrypt "$ARCHIVE"
    rm -f "$ARCHIVE"
    ARCHIVE="${ARCHIVE}.gpg"
    # Test decryption
    if gpg --batch --list-packets "$ARCHIVE" > /dev/null 2>&1; then
        log "Encryption test passed"
    fi
elif [[ "$ENCRYPTION" == "age" && -n "$ENCRYPTION_KEY" ]]; then
    log "Encrypting with age..."
    age -r "$ENCRYPTION_KEY" -o "${ARCHIVE}.age" "$ARCHIVE"
    rm -f "$ARCHIVE"
    ARCHIVE="${ARCHIVE}.age"
fi

# --- 8. Optional upload ---
if [[ "$UPLOAD_METHOD" == "rclone" && -n "$UPLOAD_TARGET" ]]; then
    log "Uploading to ${UPLOAD_TARGET}..."
    rclone copy "$ARCHIVE" "$UPLOAD_TARGET" || log "WARNING: Upload failed"
fi

# --- 9. Retention ---
log "Applying retention policy (${RETENTION_DAILY} daily, ${RETENTION_WEEKLY} weekly)..."
# Keep N most recent daily backups
find "$BACKUP_DIR" -name 'matrix-backup-*.tar.gz*' -type f | sort -r | tail -n +$((RETENTION_DAILY + RETENTION_WEEKLY + 1)) | while read -r old; do
    log "Removing old backup: $(basename "$old")"
    rm -f "$old"
done

log "Backup completed: $(basename "$ARCHIVE") ($(du -h "$ARCHIVE" | cut -f1))"
BKEOF

    chmod 750 "$scripts_dir/backup.sh"
    rollback_snapshot "backup" "FILE_CREATED" "$scripts_dir/backup.sh"
    log_substep "Backup script generated: $scripts_dir/backup.sh"
}

_backup_generate_restore_script() {
    local scripts_dir="$1"
    local install_dir="$2"
    local domain="$3"

    {
        printf '#!/usr/bin/env bash\n'
        printf '# Matrix Stack Restore Script\n'
        printf '# Generated by Matrix Stack Setup — do not edit manually.\n'
        printf 'set -euo pipefail\n\n'
        printf 'INSTALL_DIR=%q\n' "$install_dir"
        printf 'DOMAIN=%q\n'      "$domain"
        printf 'DRY_RUN=false\n'
    } > "$scripts_dir/restore.sh"

    cat >> "$scripts_dir/restore.sh" << 'RSTEOF'

usage() {
    echo "Usage: $0 [--dry-run] <backup-archive>"
    echo "  --dry-run   Validate backup without restoring"
    exit 1
}

log() { printf '[%s] %s\n' "$(date -u +%Y-%m-%dT%H:%M:%SZ)" "$*"; }

# Parse args
while [[ $# -gt 0 ]]; do
    case "$1" in
        --dry-run) DRY_RUN=true; shift ;;
        -h|--help) usage ;;
        *) ARCHIVE="$1"; shift ;;
    esac
done

[[ -z "${ARCHIVE:-}" ]] && usage
[[ -f "$ARCHIVE" ]] || { log "ERROR: Archive not found: $ARCHIVE"; exit 1; }

# Decrypt if needed
if [[ "$ARCHIVE" == *.gpg ]]; then
    log "Decrypting GPG archive..."
    DECRYPTED="${ARCHIVE%.gpg}"
    gpg --batch --yes --decrypt -o "$DECRYPTED" "$ARCHIVE"
    ARCHIVE="$DECRYPTED"
elif [[ "$ARCHIVE" == *.age ]]; then
    log "Decrypting age archive..."
    DECRYPTED="${ARCHIVE%.age}"
    age --decrypt -o "$DECRYPTED" "$ARCHIVE"
    ARCHIVE="$DECRYPTED"
fi

WORK_DIR=$(mktemp -d /tmp/matrix-restore.XXXXXXXXXX)
trap 'rm -rf "$WORK_DIR"' EXIT

log "Extracting archive..."
tar -xzf "$ARCHIVE" -C "$WORK_DIR"
BACKUP_DIR=$(find "$WORK_DIR" -maxdepth 1 -type d -name 'matrix-backup-*' | head -1)
[[ -n "$BACKUP_DIR" ]] || { log "ERROR: Invalid backup archive"; exit 1; }

# --- Signing key verification ---
log "Verifying signing key..."
if [[ -d "$BACKUP_DIR/signing-keys" ]]; then
    if [[ -d "$INSTALL_DIR/data/signing-keys" ]]; then
        # Compare key fingerprints
        BACKUP_KEY=$(find "$BACKUP_DIR/signing-keys" -name '*.signing.key' | head -1)
        CURRENT_KEY=$(find "$INSTALL_DIR/data/signing-keys" -name '*.signing.key' | head -1)
        if [[ -n "$BACKUP_KEY" && -n "$CURRENT_KEY" ]]; then
            if ! diff -q "$BACKUP_KEY" "$CURRENT_KEY" > /dev/null 2>&1; then
                log "WARNING: Signing key in backup does NOT match current key!"
                log "Restoring this backup may cause federation issues."
                read -rp "Continue anyway? [y/N]: " confirm
                [[ "$confirm" == "y" ]] || exit 1
            else
                log "Signing key matches current installation"
            fi
        fi
    fi
else
    log "WARNING: No signing key found in backup!"
fi

# --- Database integrity check ---
log "Checking database dump integrity..."
if [[ -f "$BACKUP_DIR/database.dump" ]]; then
    if pg_restore --list "$BACKUP_DIR/database.dump" > /dev/null 2>&1; then
        log "Database dump integrity: OK"
    else
        log "WARNING: Database dump integrity check failed"
    fi
else
    log "WARNING: No database dump found in backup"
fi

# Metadata
if [[ -f "$BACKUP_DIR/backup-metadata.txt" ]]; then
    log "Backup metadata:"
    cat "$BACKUP_DIR/backup-metadata.txt" | while read -r line; do log "  $line"; done
fi

if [[ "$DRY_RUN" == "true" ]]; then
    log "Dry run complete — backup appears valid"
    exit 0
fi

log "=== RESTORING (this will overwrite current data) ==="
read -rp "Are you sure? Type 'yes' to continue: " confirm
[[ "$confirm" == "yes" ]] || { log "Aborted."; exit 0; }

# Stop services
log "Stopping Matrix stack..."
podman compose -f "$INSTALL_DIR/podman-compose.yml" down 2>/dev/null || true

# Restore database
if [[ -f "$BACKUP_DIR/database.dump" ]]; then
    log "Restoring database..."
    podman compose -f "$INSTALL_DIR/podman-compose.yml" up -d postgres
    sleep 5
    podman exec -i matrix-postgres pg_restore -U synapse -d synapse --clean --if-exists < "$BACKUP_DIR/database.dump" 2>/dev/null || true
    log "Database restored"
fi

# Restore signing keys
if [[ -d "$BACKUP_DIR/signing-keys" ]]; then
    log "Restoring signing keys..."
    cp -a "$BACKUP_DIR/signing-keys/"* "$INSTALL_DIR/data/signing-keys/"
fi

# Restore media
if [[ -d "$BACKUP_DIR/media" ]]; then
    log "Restoring media store..."
    cp -a "$BACKUP_DIR/media/"* "$INSTALL_DIR/data/media/"
fi

# Restore config
if [[ -d "$BACKUP_DIR/config" ]]; then
    log "Restoring configuration..."
    cp -a "$BACKUP_DIR/config/"* "$INSTALL_DIR/config/"
fi

# Restart services
log "Starting Matrix stack..."
podman compose -f "$INSTALL_DIR/podman-compose.yml" up -d

log "Restore completed. Verify services are running."
RSTEOF

    chmod 750 "$scripts_dir/restore.sh"
    rollback_snapshot "backup" "FILE_CREATED" "$scripts_dir/restore.sh"
    log_substep "Restore script generated: $scripts_dir/restore.sh"
}

_backup_install_timer() {
    local install_dir="$1"
    local matrix_user="${CONFIG[matrix_user]:-$DEFAULT_MATRIX_USER}"
    local user_home
    user_home=$(get_user_home "$matrix_user")
    local timer_dir="${user_home}/.config/systemd/user"

    mkdir -p "$timer_dir"

    cat > "$timer_dir/matrix-backup.service" << UNIT
[Unit]
Description=Matrix Stack Backup

[Service]
Type=oneshot
ExecStart=${install_dir}/scripts/backup.sh
StandardOutput=journal
StandardError=journal
UNIT

    cat > "$timer_dir/matrix-backup.timer" << UNIT
[Unit]
Description=Daily Matrix backup

[Timer]
OnCalendar=*-*-* 03:00:00
RandomizedDelaySec=1800
Persistent=true

[Install]
WantedBy=timers.target
UNIT

    chown -R "${matrix_user}:" "$timer_dir"
    run_as_user systemctl --user enable matrix-backup.timer 2>/dev/null || true

    rollback_snapshot "backup" "TIMER_INSTALLED" "$timer_dir/matrix-backup.timer"
    log_substep "Backup timer installed (daily at 03:00)"
}
