#!/usr/bin/env bash
# Matrix Stack Setup - Media Retention
# Reports the remote-media retention policy in force and watches the media
# store's disk usage on a weekly timer.
#
# This phase used to generate a script that POSTed to
# http://localhost:8008/_synapse/admin/v1/purge_media_cache. That call could
# never succeed, for two independent reasons:
#
#   * Both homeserver fragments declare `ports: []`, so nothing the homeserver
#     serves is published to the host and a host-side request to port 8008
#     cannot connect (see lib/21_deploy.sh, which routes its own probes through
#     the container for the same reason).
#   * The call authenticated with a token read from $install_dir/.admin-token,
#     which nothing in this repository ever writes. Synapse's media admin API
#     requires a server-admin access token (Synapse v1.127.1,
#     docs/admin_api/media_admin_api.md), so an empty bearer would be rejected
#     even from inside the container.
#
# Routing it through `podman exec` would have fixed the first and left the
# second. It is not needed at all: Synapse purges its own remote media cache
# from `media_retention.remote_media_lifetime`, which
# templates/configs/homeserver.synapse.yaml.tpl already renders. Both mechanisms
# use the same criterion - Synapse's config option purges media "if it has not
# been accessed in a given amount of time" (v1.127.1
# docs/usage/configuration/config_documentation.md, `media_retention`), and
# purge_media_cache removes "all cached media that was last accessed before
# this timestamp" (media_admin_api.md). The timer therefore reports the policy
# rather than duplicating it.
set -euo pipefail

media_retention_setup() {
    log_step "Configuring media retention"

    local install_dir="${CONFIG[install_dir]:-$DEFAULT_INSTALL_DIR}"
    local matrix_user="${CONFIG[matrix_user]:-$DEFAULT_MATRIX_USER}"
    local hs_type="${CONFIG[homeserver.type]:-synapse}"
    local user_home
    user_home=$(get_user_home "$matrix_user")
    local timer_dir="${user_home}/.config/systemd/user"
    local retention_days="${CONFIG[media_retention.days]:-$DEFAULT_MEDIA_RETENTION_DAYS}"

    # backup_setup happens to create the scripts directory first, but nothing
    # declares that ordering, so this phase makes its own.
    mkdir -p "$timer_dir" "$install_dir/scripts"

    # The policy line is baked into the generated script at install time, so
    # the script needs no config file, no CONFIG array and no homeserver to
    # tell the operator what is (and is not) being enforced.
    #
    # Dendrite v0.14.1 has no remote-media retention to report: its client API
    # registers no media-purge admin route (clientapi/routing.go registers
    # evacuateRoom, evacuateUser, purgeRoom, resetPassword, downloadState,
    # fulltext/reindex, refreshDevices and registrationTokens, plus the two
    # Synapse-compatible routes register and send_server_notice), its media API
    # serves only upload, download, thumbnail and config
    # (mediaapi/routing/routing.go), and its MediaAPI config has no retention
    # or lifetime option (setup/config/config_mediaapi.go).
    local policy_line unit_description
    if [[ "$hs_type" == "dendrite" ]]; then
        policy_line="NOTE: Dendrite has no remote-media retention, so the media store grows without bound. Prune it by hand when this check warns."
        unit_description="Matrix media store disk check"
        log_warn "Dendrite has no remote-media retention: it exposes no media-purge admin API and no retention setting."
        log_warn "media_retention.days (${retention_days}) has no effect on Dendrite; the weekly timer reports disk usage only."
    elif [[ "${CONFIG[federation.enabled]:-true}" != "true" ]]; then
        policy_line="Federation is disabled, so this server holds no remote media cache to purge."
        unit_description="Matrix media store disk check"
    else
        policy_line="Remote media cache retention: ${retention_days} days, purged by Synapse itself via media_retention.remote_media_lifetime in homeserver.yaml."
        unit_description="Matrix media retention check"
    fi

    # Nothing below runs during setup: it runs weeks later from a user timer,
    # as the matrix user, with none of this file in scope. It therefore does no
    # HTTP, needs no credential and does not touch the container - it reads a
    # host bind mount, so it behaves the same whether the stack is up or down.
    cat > "$install_dir/scripts/media-cleanup.sh" << SCRIPT
#!/usr/bin/env bash
# Matrix media store check - generated by Matrix Stack Setup.
# Run weekly by matrix-media-cleanup.timer as the matrix user.
set -euo pipefail

MEDIA_DIR="${install_dir}/data/media"

log() { printf '[%s] %s\n' "\$(date -u +%Y-%m-%dT%H:%M:%SZ)" "\$*"; }

log "${policy_line}"

if [[ ! -d "\$MEDIA_DIR" ]]; then
    log "Media directory \$MEDIA_DIR does not exist; nothing to check."
    exit 0
fi

USAGE=\$(df "\$MEDIA_DIR" --output=pcent | tail -1 | tr -d ' %')
if (( USAGE >= 90 )); then
    log "ALERT: Disk usage at \${USAGE}%, consider expanding storage"
elif (( USAGE >= 80 )); then
    log "WARNING: Disk usage at \${USAGE}%"
else
    log "Disk usage at \${USAGE}%"
fi

log "Media check completed"
SCRIPT

    chmod 750 "$install_dir/scripts/media-cleanup.sh"

    # Systemd timer
    cat > "$timer_dir/matrix-media-cleanup.service" << UNIT
[Unit]
Description=${unit_description}

[Service]
Type=oneshot
ExecStart=${install_dir}/scripts/media-cleanup.sh
StandardOutput=journal
StandardError=journal
UNIT

    cat > "$timer_dir/matrix-media-cleanup.timer" << UNIT
[Unit]
Description=Weekly ${unit_description}

[Timer]
OnCalendar=Sun *-*-* 04:00:00
RandomizedDelaySec=3600
Persistent=true

[Install]
WantedBy=timers.target
UNIT

    chown -R "${matrix_user}:" "$timer_dir"
    run_as_user systemctl --user enable matrix-media-cleanup.timer 2>/dev/null || true

    rollback_snapshot "media" "TIMER_INSTALLED" "$timer_dir/matrix-media-cleanup.timer"
    log_substep "Media check timer installed (weekly)"
    log_success "Media retention configured"
}
