# Apache reverse proxy snippet for Matrix — generated by Matrix Stack Setup
# Enable modules: a2enmod proxy proxy_http proxy_wstunnel headers rewrite

# .well-known endpoints
<Location "/.well-known/matrix/client">
    Header set Content-Type "application/json"
    Header set Access-Control-Allow-Origin "*"
    RewriteEngine On
    RewriteRule ^(.*)$ - [R=200,L]
    ErrorDocument 200 '{"m.homeserver":{"base_url":"https://{{DOMAIN}}"}}'
</Location>

<Location "/.well-known/matrix/server">
    Header set Content-Type "application/json"
    RewriteEngine On
    RewriteRule ^(.*)$ - [R=200,L]
    ErrorDocument 200 '{"m.server":"{{DOMAIN}}:443"}'
</Location>

# Proxy Matrix APIs
<Location "/_matrix">
    ProxyPass http://127.0.0.1:{{HS_PORT}}/_matrix
    ProxyPassReverse http://127.0.0.1:{{HS_PORT}}/_matrix
    ProxyPreserveHost On
    RequestHeader set X-Forwarded-Proto "https"
</Location>

<Location "/_synapse">
    ProxyPass http://127.0.0.1:{{HS_PORT}}/_synapse
    ProxyPassReverse http://127.0.0.1:{{HS_PORT}}/_synapse
    ProxyPreserveHost On
    RequestHeader set X-Forwarded-Proto "https"
</Location>

# WebSocket support for /sync
RewriteEngine On
RewriteCond %{HTTP:Upgrade} =websocket [NC]
RewriteRule /_matrix/(.*) ws://127.0.0.1:{{HS_PORT}}/_matrix/$1 [P,L]
