Matrix Reverse Proxy Requirements — generated by Matrix Stack Setup
===================================================================
Domain: {{DOMAIN}}
Homeserver backend: http://{{HS_HOST}}:{{HS_PORT}}

Backend reachability:
  The generated compose file publishes the homeserver's client port on
  {{HS_HOST}}:{{HS_PORT}} whenever setup defers to an existing proxy, so these
  routes reach it as written. If your proxy runs anywhere but this host, set
  proxy.bind_address to an address it can reach and re-run setup.

Required routes:
  /_matrix/*              -> http://{{HS_HOST}}:{{HS_PORT}}
  /_synapse/*             -> http://{{HS_HOST}}:{{HS_PORT}}
  /.well-known/matrix/*   -> http://{{HS_HOST}}:{{HS_PORT}}

The homeserver answers /.well-known/matrix/client and
/.well-known/matrix/server itself, so proxying them is enough. If you would
rather answer them at the proxy, the bodies are:
  /.well-known/matrix/server  -> {"m.server":"{{DOMAIN}}:443"}
  /.well-known/matrix/client  -> {"m.homeserver":{"base_url":"https://{{DOMAIN}}"}}

Required headers:
  Strict-Transport-Security: max-age=63072000; includeSubDomains; preload
  X-Content-Type-Options: nosniff
  X-Frame-Options: DENY
  Referrer-Policy: strict-origin-when-cross-origin
  Access-Control-Allow-Origin: * (on .well-known endpoints)

WebSocket upgrade required for:
  /_matrix/client/*/sync

Max upload size: 100MB (client_max_body_size or equivalent)
