Matrix Reverse Proxy Requirements — generated by Matrix Stack Setup
===================================================================
Domain: {{DOMAIN}}
Homeserver backend: http://127.0.0.1:{{HS_PORT}}

Backend reachability:
  The generated compose file publishes no homeserver port (both homeserver
  fragments declare `ports: []`). Publish the container port, or attach your
  proxy to the matrix-net network, before these routes will connect.

Required routes:
  /_matrix/*              -> http://127.0.0.1:{{HS_PORT}}
  /_synapse/*             -> http://127.0.0.1:{{HS_PORT}}
  /.well-known/matrix/*   -> http://127.0.0.1:{{HS_PORT}}

The homeserver answers /.well-known/matrix/client and
/.well-known/matrix/server itself, so proxying them is enough. If you would
rather answer them at the proxy, the bodies are:
  /.well-known/matrix/server  -> {"m.server":"{{DOMAIN}}:443"}
  /.well-known/matrix/client  -> {"m.homeserver":{"base_url":"https://{{DOMAIN}}"}}

Required headers:
  Strict-Transport-Security: max-age=63072000; includeSubDomains; preload
  X-Content-Type-Options: nosniff
  X-Frame-Options: DENY
  Referrer-Policy: strict-origin-when-cross-origin
  Access-Control-Allow-Origin: * (on .well-known endpoints)

WebSocket upgrade required for:
  /_matrix/client/*/sync

Max upload size: 100MB (client_max_body_size or equivalent)
