# nginx reverse proxy snippet for Matrix — generated by Matrix Stack Setup
# Add this to your existing nginx server block or include it.
#
# Backend reachability: the generated compose file publishes the homeserver's
# client port on {{HS_HOST}}:{{HS_PORT}} whenever setup defers to an existing
# proxy, so these routes reach it as written. If nginx runs anywhere but this
# host, set proxy.bind_address to an address it can reach and re-run setup.
#
# The security headers are repeated in every location below rather than set
# once at server level: nginx inherits add_header from the enclosing level
# "if and only if there are no add_header directives defined on the current
# level" (nginx docs, ngx_http_headers_module, add_header), and each location
# here defines its own. Setting them only in your server block would leave
# these locations without them.

# .well-known for Matrix client discovery
location /.well-known/matrix/client {
    default_type application/json;
    add_header Access-Control-Allow-Origin * always;
    add_header Strict-Transport-Security "max-age=63072000; includeSubDomains; preload" always;
    add_header X-Content-Type-Options "nosniff" always;
    add_header X-Frame-Options "DENY" always;
    add_header Referrer-Policy "strict-origin-when-cross-origin" always;
    return 200 '{"m.homeserver":{"base_url":"https://{{DOMAIN}}"}}';
}

# .well-known for Matrix server discovery (federation)
location /.well-known/matrix/server {
    default_type application/json;
    add_header Access-Control-Allow-Origin * always;
    add_header Strict-Transport-Security "max-age=63072000; includeSubDomains; preload" always;
    add_header X-Content-Type-Options "nosniff" always;
    add_header X-Frame-Options "DENY" always;
    add_header Referrer-Policy "strict-origin-when-cross-origin" always;
    return 200 '{"m.server":"{{DOMAIN}}:443"}';
}

# Proxy Matrix client and federation APIs
location /_matrix/ {
    proxy_pass http://{{HS_HOST}}:{{HS_PORT}};
    proxy_set_header X-Forwarded-For $remote_addr;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header Host $host;

    add_header Strict-Transport-Security "max-age=63072000; includeSubDomains; preload" always;
    add_header X-Content-Type-Options "nosniff" always;
    add_header X-Frame-Options "DENY" always;
    add_header Referrer-Policy "strict-origin-when-cross-origin" always;

    # WebSocket support
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";

    # Timeouts for long-polling /sync
    proxy_read_timeout 600s;
    proxy_send_timeout 600s;
    proxy_buffering off;

    client_max_body_size 100M;
}

# Synapse admin API
location /_synapse/ {
    proxy_pass http://{{HS_HOST}}:{{HS_PORT}};
    proxy_set_header X-Forwarded-For $remote_addr;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header Host $host;

    add_header Strict-Transport-Security "max-age=63072000; includeSubDomains; preload" always;
    add_header X-Content-Type-Options "nosniff" always;
    add_header X-Frame-Options "DENY" always;
    add_header Referrer-Policy "strict-origin-when-cross-origin" always;
}
