# nginx reverse proxy snippet for Matrix — generated by Matrix Stack Setup
# Add this to your existing nginx server block or include it.

# .well-known for Matrix client discovery
location /.well-known/matrix/client {
    default_type application/json;
    add_header Access-Control-Allow-Origin *;
    return 200 '{"m.homeserver":{"base_url":"https://{{DOMAIN}}"}}';
}

# .well-known for Matrix server discovery (federation)
location /.well-known/matrix/server {
    default_type application/json;
    return 200 '{"m.server":"{{DOMAIN}}:443"}';
}

# Proxy Matrix client and federation APIs
location /_matrix/ {
    proxy_pass http://127.0.0.1:{{HS_PORT}};
    proxy_set_header X-Forwarded-For $remote_addr;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header Host $host;

    # WebSocket support
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";

    # Timeouts for long-polling /sync
    proxy_read_timeout 600s;
    proxy_send_timeout 600s;

    client_max_body_size 100M;
}

# Synapse admin API
location /_synapse/ {
    proxy_pass http://127.0.0.1:{{HS_PORT}};
    proxy_set_header X-Forwarded-For $remote_addr;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header Host $host;
}
