# Traefik dynamic config snippet for Matrix — generated by Matrix Stack Setup
# Add to your Traefik dynamic configuration directory.
#
# Backend reachability: these services assume 127.0.0.1:{{HS_PORT}} reaches the
# homeserver. The generated compose file publishes no homeserver port (both
# fragments declare `ports: []`), so publish the container port or attach
# Traefik to the matrix-net network first.

http:
  middlewares:
    # Option names per Traefik's headers middleware documentation.
    matrix-security-headers:
      headers:
        stsSeconds: 63072000
        stsIncludeSubdomains: true
        stsPreload: true
        contentTypeNosniff: true
        frameDeny: true
        referrerPolicy: "strict-origin-when-cross-origin"

  routers:
    matrix:
      rule: "Host(`{{DOMAIN}}`)"
      service: matrix-homeserver
      middlewares:
        - matrix-security-headers
      entryPoints:
        - websecure
      tls:
        certResolver: letsencrypt

    # Both homeservers serve /.well-known/matrix themselves (Synapse from
    # public_baseurl and serve_server_wellknown, Dendrite from
    # global.well_known_client_name and well_known_server_name), so the
    # delegation is proxied rather than restated here.
    matrix-wellknown:
      rule: "Host(`{{DOMAIN}}`) && PathPrefix(`/.well-known/matrix`)"
      service: matrix-homeserver
      middlewares:
        - matrix-security-headers
      entryPoints:
        - websecure
      tls:
        certResolver: letsencrypt

{{#WEBCLIENT}}
    matrix-webclient:
      rule: "Host(`{{WEBCLIENT_SUBDOMAIN}}.{{DOMAIN}}`)"
      service: matrix-webclient
      middlewares:
        - matrix-security-headers
      entryPoints:
        - websecure
      tls:
        certResolver: letsencrypt
{{/WEBCLIENT}}

  services:
    matrix-homeserver:
      loadBalancer:
        servers:
          - url: "http://127.0.0.1:{{HS_PORT}}"

{{#WEBCLIENT}}
    matrix-webclient:
      loadBalancer:
        servers:
          - url: "http://127.0.0.1:8080"
{{/WEBCLIENT}}
