# Traefik dynamic config snippet for Matrix — generated by Matrix Stack Setup
# Add to your Traefik dynamic configuration directory.

http:
  routers:
    matrix:
      rule: "Host(`{{DOMAIN}}`)"
      service: matrix-homeserver
      entryPoints:
        - websecure
      tls:
        certResolver: letsencrypt

    matrix-wellknown:
      rule: "Host(`{{DOMAIN}}`) && PathPrefix(`/.well-known/matrix`)"
      service: matrix-homeserver
      entryPoints:
        - websecure
      tls:
        certResolver: letsencrypt

{{#WEBCLIENT}}
    matrix-webclient:
      rule: "Host(`{{WEBCLIENT_SUBDOMAIN}}.{{DOMAIN}}`)"
      service: matrix-webclient
      entryPoints:
        - websecure
      tls:
        certResolver: letsencrypt
{{/WEBCLIENT}}

  services:
    matrix-homeserver:
      loadBalancer:
        servers:
          - url: "http://127.0.0.1:{{HS_PORT}}"

{{#WEBCLIENT}}
    matrix-webclient:
      loadBalancer:
        servers:
          - url: "http://127.0.0.1:8080"
{{/WEBCLIENT}}
