# Traefik dynamic config snippet for Matrix — generated by Matrix Stack Setup
# Add to your Traefik dynamic configuration directory.
#
# Backend reachability: the generated compose file publishes the homeserver's
# client port on {{HS_HOST}}:{{HS_PORT}} whenever setup defers to an existing
# proxy, so these services reach it as written. If Traefik runs anywhere but
# this host, set proxy.bind_address to an address it can reach and re-run setup.

http:
  middlewares:
    # Option names per Traefik's headers middleware documentation.
    matrix-security-headers:
      headers:
        stsSeconds: 63072000
        stsIncludeSubdomains: true
        stsPreload: true
        contentTypeNosniff: true
        frameDeny: true
        referrerPolicy: "strict-origin-when-cross-origin"

  routers:
    matrix:
      rule: "Host(`{{DOMAIN}}`)"
      service: matrix-homeserver
      middlewares:
        - matrix-security-headers
      entryPoints:
        - websecure
      tls:
        certResolver: letsencrypt

    # Both homeservers serve /.well-known/matrix themselves (Synapse from
    # public_baseurl and serve_server_wellknown, Dendrite from
    # global.well_known_client_name and well_known_server_name), so the
    # delegation is proxied rather than restated here.
    matrix-wellknown:
      rule: "Host(`{{DOMAIN}}`) && PathPrefix(`/.well-known/matrix`)"
      service: matrix-homeserver
      middlewares:
        - matrix-security-headers
      entryPoints:
        - websecure
      tls:
        certResolver: letsencrypt

{{#WEBCLIENT}}
    matrix-webclient:
      rule: "Host(`{{WEBCLIENT_SUBDOMAIN}}.{{DOMAIN}}`)"
      service: matrix-webclient
      middlewares:
        - matrix-security-headers
      entryPoints:
        - websecure
      tls:
        certResolver: letsencrypt
{{/WEBCLIENT}}

  services:
    matrix-homeserver:
      loadBalancer:
        servers:
          - url: "http://{{HS_HOST}}:{{HS_PORT}}"

{{#WEBCLIENT}}
    matrix-webclient:
      loadBalancer:
        servers:
          - url: "http://{{HS_HOST}}:{{WEBCLIENT_PORT}}"
{{/WEBCLIENT}}
