# SSH hardening drop-in — generated by Matrix Stack Setup
# Placed at /etc/ssh/sshd_config.d/99-matrix-hardening.conf

PasswordAuthentication no
PubkeyAuthentication yes
PermitRootLogin no
MaxAuthTries 3
X11Forwarding no
AllowTcpForwarding no
ClientAliveInterval 300
ClientAliveCountMax 2
