# Matrix Stack SSH Hardening — generated by Matrix Stack Setup
# Placed at /etc/ssh/sshd_config.d/99-matrix-hardening.conf

PasswordAuthentication no
PermitRootLogin no
PubkeyAuthentication yes
AuthenticationMethods publickey
X11Forwarding no
MaxAuthTries 3
ClientAliveInterval 300
ClientAliveCountMax 2
{{#SSH_NO_TCP_FORWARDING}}
# hardening.ssh_tcp_forwarding = false. Only emitted when the operator asks for
# it: staying silent otherwise leaves whatever their own sshd_config sets, and
# this drop-in is included ahead of it.
AllowTcpForwarding no
{{/SSH_NO_TCP_FORWARDING}}
