# fail2ban jails for Matrix/Synapse and SSH — generated by Matrix Stack Setup
# Placed at /etc/fail2ban/jail.d/matrix.conf

{{#SYNAPSE_JAIL}}
[matrix-synapse]
enabled = true
port = {{HTTPS_PORT}},{{FEDERATION_PORT}}
filter = matrix-synapse
logpath = {{SYNAPSE_LOG_PATH}}
maxretry = 5
findtime = 300
bantime = 3600
backend = auto

{{/SYNAPSE_JAIL}}
[sshd]
enabled = true
maxretry = 3
findtime = 300
bantime = 3600
