# fail2ban jail for Matrix/Synapse — generated by Matrix Stack Setup
# Placed at /etc/fail2ban/jail.d/matrix-synapse.conf

[matrix-synapse]
enabled  = true
port     = http,https
filter   = matrix-synapse
logpath  = {{INSTALL_DIR}}/data/logs/homeserver.log
maxretry = 5
findtime = 300
bantime  = 3600
action   = %(action_)s
