# fail2ban filter for Matrix/Synapse — generated by Matrix Stack Setup
# Placed at /etc/fail2ban/filter.d/matrix-synapse.conf

[Definition]
failregex = ^.* Received request:.*from <HOST>.*\s403\s
            ^.* Failed password login.*from <HOST>
            ^.* \[.*\] <HOST> .* 403 .*$

ignoreregex =
