# fail2ban filter for Matrix/Synapse — generated by Matrix Stack Setup
# Placed at /etc/fail2ban/filter.d/matrix-synapse.conf
#
# UNVERIFIED: these patterns have never been checked against a real Synapse
# auth-failure log line taken from Synapse's own source or documentation. They
# are carried over unchanged from the inline definition they replace, so this
# file is not a behaviour change — but nothing here is evidence that the jail
# matches anything Synapse actually writes. Verify against a captured log line
# before relying on it.

[Definition]
failregex = ^.* Received request: POST /_matrix/client/.*/login.*from <HOST>.*$
            ^.* Failed password login attempt.*from <HOST>.*$
            ^.*\[synapse\.rest\.client\.login\].*<HOST>.*403.*$
ignoreregex =
