# Sysctl tuning — generated by Matrix Stack Setup
# Placed at /etc/sysctl.d/99-matrix-hardening.conf

# Allow rootless containers to bind ports 80/443
net.ipv4.ip_unprivileged_port_start=80

# TCP SYN flood protection
net.ipv4.tcp_syncookies=1

# Reverse path filtering (strict)
net.ipv4.conf.all.rp_filter=1
net.ipv4.conf.default.rp_filter=1

# ICMP limits
net.ipv4.icmp_echo_ignore_broadcasts=1
net.ipv4.icmp_ignore_bogus_error_responses=1
net.ipv4.icmp_ratelimit=100

# Disable source routing
net.ipv4.conf.all.accept_source_route=0
net.ipv6.conf.all.accept_source_route=0

# Disable redirects
net.ipv4.conf.all.accept_redirects=0
net.ipv6.conf.all.accept_redirects=0
net.ipv4.conf.all.send_redirects=0

# IPv6 privacy extensions
net.ipv6.conf.all.use_tempaddr=2
net.ipv6.conf.default.use_tempaddr=2

# Connection tracking tuning for containers
net.netfilter.nf_conntrack_max=131072
