# Sysctl hardening — generated by Matrix Stack Setup
# Placed at /etc/sysctl.d/99-matrix.conf

# Allow rootless Podman to bind ports 80/443.
#
# Caddy runs as an ordinary user, so without this it cannot listen on 443 and
# cannot get a TLS certificate. The trade-off: this also lets every other
# account on this machine bind ports 80-1023. Someone with a shell account here
# could grab port 80 before Caddy does and take over certificate issuance for
# your domain.
#
# That is an acceptable trade for one admin running a server for a small group,
# which is what this setup assumes. It is not acceptable on a machine you share:
# do not hand out shell accounts on the box that terminates your TLS. If you
# need to, delete this line, run the stack as root instead, and re-run setup.
net.ipv4.ip_unprivileged_port_start=80

# Network hardening
net.core.somaxconn=1024
net.ipv4.tcp_syncookies=1
net.ipv4.conf.all.rp_filter=1
net.ipv4.conf.default.rp_filter=1
net.ipv4.icmp_echo_ignore_broadcasts=1
net.ipv4.conf.all.accept_redirects=0
net.ipv4.conf.default.accept_redirects=0
net.ipv4.conf.all.send_redirects=0
net.ipv6.conf.all.accept_redirects=0
net.ipv6.conf.default.accept_redirects=0

# Reduce information disclosure
net.ipv4.icmp_ignore_bogus_error_responses=1
{{#IPV6_PRIVACY}}

# hardening.ipv6_privacy = true. RFC 4941 privacy addresses: 2 = prefer the
# temporary address over the stable one for outgoing connections. Only affects
# addresses obtained by autoconfiguration.
net.ipv6.conf.all.use_tempaddr=2
net.ipv6.conf.default.use_tempaddr=2
{{/IPV6_PRIVACY}}
{{#CONNTRACK_MAX_SET}}

# hardening.conntrack_max. Written only when the running kernel exposes the key.
net.netfilter.nf_conntrack_max={{CONNTRACK_MAX}}
{{/CONNTRACK_MAX_SET}}
